[project]
name = "backend"
version = "0.1.0"
description = "Backend for the codingX application"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.13",
    "uvicorn>=0.34.3",
]
